name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.0'

      - name: Install Boost
        run: |
          choco install boost-msvc --version=1.89.0 -y
          refreshenv

      - name: Configure project
        run: cmake . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_NUMBER=${{ github.run_number }}

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest -C Release --output-on-failure
